from .article_comparison.avrachenkov_tests import *
from .article_comparison.chebotarev_tests import *
from .article_comparison.kivimaki_tests import *
from .article_comparison.sommer_tests import *
from .article_comparison.yen_tests import *
from .gpdistance_tests import *
from .measure_common_tests import *
from .spct_tests import *
from .workflow_tests import *
